# Generated by Django 2.0 on 2019-01-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(max_length=2)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myclass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('Registration_Number', models.CharField(max_length=12, unique=True)),
                ('Phone', models.CharField(default='+234', max_length=30)),
                ('Address', models.CharField(max_length=600)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Father_Name', models.CharField(max_length=220)),
                ('Mother_Name', models.CharField(max_length=220)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Passport', models.FileField(blank=True, upload_to='')),
                ('current_class', models.CharField(choices=[('kg1', 'kg1'), ('kg2', 'kg2'), ('kg3', 'kg3'), ('pry1', 'pry1'), ('pry2', 'pry2'), ('pry3', 'pry3'), ('pry4', 'pry4'), ('pry5', 'pry5'), ('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], default='', max_length=5)),
                ('current_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.CharField(default='', max_length=5)),
                ('first_test', models.PositiveIntegerField(default=0)),
                ('second_test', models.PositiveIntegerField(default=0)),
                ('exam', models.PositiveIntegerField(default=0)),
                ('average', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=1000)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.PositiveIntegerField(default=0)),
                ('second_test', models.PositiveIntegerField(default=0)),
                ('exam', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('no', models.CharField(default='0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st term'), ('2nd term', '2nd term'), ('3rd term', '3rd term')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Subject'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Subject'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session'),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='qs',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='administrator.Student'),
        ),
        migrations.AddField(
            model_name='currentterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='currentsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session'),
        ),
    ]
