# Generated by Django 2.0 on 2019-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190119_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
