# Generated by Django 2.0 on 2019-01-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_student_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalresult',
            name='qs',
        ),
        migrations.AddField(
            model_name='generalresult',
            name='Registration_Number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='current_class',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='middle_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='session',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generalresult',
            name='term',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalresult',
            name='grade',
            field=models.CharField(default='', max_length=3),
        ),
    ]
