# Generated by Django 2.0 on 2019-01-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190119_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalresult',
            old_name='session',
            new_name='current_session',
        ),
        migrations.RenameField(
            model_name='generalresult',
            old_name='term',
            new_name='current_term',
        ),
    ]
