# Generated by Django 2.0 on 2019-01-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190119_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresult',
            name='position',
            field=models.CharField(default='', max_length=500),
        ),
    ]
