# Generated by Django 2.0 on 2019-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20190119_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalresult',
            name='total_subject',
            field=models.CharField(default='', max_length=30),
        ),
    ]
