# Generated by Django 2.0 on 2019-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_generalresult_total_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.CharField(default='', max_length=3),
        ),
    ]
