# Generated by Django 2.0 on 2019-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_student_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalresult',
            name='percentage',
            field=models.CharField(default='', max_length=3),
        ),
    ]
