# Generated by Django 2.0 on 2019-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.CharField(default='', max_length=10),
        ),
    ]
