# Generated by Django 2.0 on 2019-01-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_remove_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=100)),
                ('Registration_Number', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
            ],
        ),
    ]
