# Generated by Django 2.0 on 2019-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_generatepin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatepin',
            name='session',
        ),
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='GeneratePin',
        ),
    ]
