# Generated by Django 2.0 on 2019-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20190122_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='session',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
