# Generated by Django 2.0 on 2019-01-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20190122_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session',
            new_name='date',
        ),
    ]
