# Generated by Django 2.0 on 2019-01-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20190122_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_subject',
            name='position',
        ),
    ]
