# Generated by Django 2.0 on 2019-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_remove_student_subject_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.PositiveIntegerField(default='0', max_length=10),
        ),
    ]
