# Generated by Django 2.0 on 2019-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20190123_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
