# Generated by Django 2.0 on 2019-01-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_student_total_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.CharField(default='', max_length=10)),
                ('pin', models.CharField(max_length=50)),
                ('Registration_Number', models.CharField(max_length=50)),
                ('current_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
            ],
        ),
    ]
