# Generated by Django 2.0 on 2019-01-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_generatepin_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatepin',
            name='Registration_Number',
        ),
    ]
