# Generated by Django 2.0 on 2019-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_remove_generatepin_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatepin',
            name='student',
        ),
        migrations.AddField(
            model_name='generatepin',
            name='Registration_Number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
