# Generated by Django 2.0 on 2019-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_auto_20190127_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepin',
            name='pin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
