# Generated by Django 2.0 on 2019-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_auto_20190127_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepin',
            name='current_session',
            field=models.CharField(max_length=50),
        ),
    ]
