# Generated by Django 2.0 on 2019-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_auto_20190127_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='term',
        ),
        migrations.AddField(
            model_name='student_subject',
            name='Registration_Number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
