# Generated by Django 2.0 on 2019-01-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_auto_20190127_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalresult',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
