# Generated by Django 2.0 on 2019-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_generalresult_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
