# Generated by Django 2.0 on 2019-01-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_newsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subject',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrator.Student'),
        ),
    ]
