# Generated by Django 2.0 on 2019-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_auto_20190129_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
