# Generated by Django 2.0 on 2019-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_newsupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
