# Generated by Django 2.0 on 2019-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_newsupdate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='published', max_length=15),
        ),
    ]
