# Generated by Django 2.0 on 2019-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsUpdate',
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
