# Generated by Django 2.0 on 2019-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0038_auto_20190130_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(),
        ),
    ]
