# Generated by Django 2.0 on 2019-02-08 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_auto_20190208_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated',
        ),
        migrations.AddField(
            model_name='news',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
